Added Blog and blog post
philippabele/nursing-home-volunteer pull request #19
Opened 2021-10-30 14:59 UTC by larsrickert

- Frontend: Added single blog post page, closes #11 
- Frontend: Added blog page that shows all blogs, filterbar needs to be implemented in separate PR
- Backend: Added blog post content type, closes #13 
- Connected frontend and backend, closes #14

2021-10-31 14:18 UTC, philippabele commented on README.md
> +1. Login to strapi
How do I login to strapi at localhost:1337 ?

2021-10-31 14:26 UTC, philippabele commented on frontend/pages/blog/index.vue
> +        console.error(e)
Why will errors only be printed to console? Does the user get no feedback, if there is an error?

2021-10-31 14:27 UTC, philippabele commented on frontend/pages/blog/index.vue
> +          <p v-if="!blogPosts.length" class="text-muted">
There should be a distinction between no blog posts from the API and an error thrown during the GET request.

2021-10-31 14:30 UTC, philippabele requested changes
The page looks good and the connection to the backend works. For the purpose of malfunction of the backend, I killed my local db and the strapi container. By running the frontend in standalone mode, I discovered only minor adjustments which need to be fixed.

2021-11-03 09:36 UTC, larsrickert commented
> The page looks good and the connection to the backend works. For the purpose of malfunction of the backend, I killed my local db and the strapi container. By running the frontend in standalone mode, I discovered only minor adjustments which need to be fixed.

Thanks. 

> The page looks good and the connection to the backend works. For the purpose of malfunction of the backend, I killed my local db and the strapi container. By running the frontend in standalone mode, I discovered only minor adjustments which need to be fixed.

Thanks. I fixed your change requests.

2021-11-04 15:40 UTC, merged